### PR TITLE
Fix white left menu on mumble-dark theme

### PR DESCRIPTION
**Pull request by cornelcristea**
Implementation:
- bat scripts for build step were  updated to user %USERNAME% environment variable
- the .gitignore file was added in order to untrack binary file generated in Build directory
- dark.qss was updated in order to fis issue https://github.com/jagannatharjun/qbt-theme/issues/75
- fixed mumble-dark.qbtheme theme was added in root dir of repo

Screenshot after fix:

image

### CODE REVIEW

**Comment by yogeshwar-b** [comment]
Thanks for this man, I tested it and it was working fine. I came here to raise the issue and fix it. Good to see someone else already did it.

**Comment by cornelcristea** [comment]
Hello,
Thank you for feedback. 
If you find a better approach, please to share with me ;)
All the best! ;)

**Comment by mariondlsu** [comment]
Hi @cornelcristea, idk how to download your fix nor do I know how to edit .qbtheme files. 

Can you share your updated .qbtheme file if it's alright with you? Thanks.

**Comment by cornelcristea** [comment]
hello @mariondlsu ,
You just clone, using git, the repo from pull request opened by me:
https://github.com/cornelcristea/qbt-theme/tree/master

And here the fixed theme will be found.

If you are not familiar with git tool, let me know and I will come back to upload the .qbtheme file. 
I just reinstalled the OS on my laptop and I have to regenerate this file :D 

Thank you!

**Comment by nuqbe** [comment]
_Hi,
thank you💗 for fixed Mumble-Dark.qbtheme.
nuqbe_

**Pull request merged**
